[package]
name = "ace"
version = "1.0.17"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.5.0"
phf = { version = "0.11.2", features = ["macros"] }
rand = "0.8.5"
